disabled_rules:
  # - colon
  # - comma
  # - control_statement
  - line_length
  # - force_try
opt_in_rules:
  # - empty_count
  - missing_docs
included:
  - Boilerplate
excluded:
  - Carthage
  - Pods

force_cast: warning
force_try:
  severity: warning
cyclomatic_complexity:
  warning: 10
  error: 30
line_length: 120
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded: iPhone
variable_name:
  min_length:
    warning: 1
  excluded:
    - id
    - URL
    - GlobalAPIKey
